### ISSUE TITLE
Виртуальные устройства перестали работать и добавлятся в умный дом Яндекса.

### ISSUE THREAD

**Issue by NE8XT** [u236/homed-service-custom#2]
УДЯ говорит - что устройства недоступны, новые  виртуальные устройства не добавляются. Правде подобно - перестало работать с последним апдейтом, с добавлением математических функций.
Локально виртуальные устройства работают в автоматизациях без замечаний.

Aqara Gateway ZHWG11LM
ARMv7 Processor rev 5 (v7l)
OpenLumi 23.05.2

root@HOMEd:~# tail -f /var/log/homed.log -n200
2024.03.13 09:10:45.035 (inf) automation: Starting version 1.3.1
2024.03.13 09:10:45.033 (inf) custom:    Starting version 1.0.5
2024.03.13 09:10:45.037 (inf) cloud:     Starting version 1.0.4
2024.03.13 09:10:45.087 (inf) custom:    Configuration file is "/etc/homed/homed-custom.conf"
2024.03.13 09:10:45.090 (inf) automation: Configuration file is "/etc/homed/homed-automation.conf"
2024.03.13 09:10:45.093 (inf) cloud:     Configuration file is "/etc/homed/homed-cloud.conf"
2024.03.13 09:10:45.184 (inf) automation: Sunrise set to 05:18 and sunset set to 17:05
2024.03.13 09:10:45.191 (wrn) cloud:     MQTT disconnected
2024.03.13 09:10:45.195 (inf) custom:    8 devices loaded
2024.03.13 09:10:45.261 (inf) custom:    Properties restored
2024.03.13 09:10:45.270 (wrn) custom:    MQTT disconnected
2024.03.13 09:10:45.302 (inf) automation: 9 automations loaded
2024.03.13 09:10:45.332 (wrn) automation: MQTT disconnected
2024.03.13 09:10:45.787 (inf) web:       Starting version 1.4.3
2024.03.13 09:10:45.792 (inf) web:       Configuration file is "/etc/homed/homed-web.conf"
2024.03.13 09:10:45.843 (wrn) web:       MQTT disconnected
2024.03.13 09:10:46.799 (inf) zigbee:    Starting version 3.7.0
2024.03.13 09:10:46.816 (inf) zigbee:    Configuration file is "/etc/homed/homed-zigbee.conf"
2024.03.13 09:10:46.890 (inf) zigbee:    Using channel 11 and PAN ID "0x1010"
2024.03.13 09:10:47.322 (wrn) cloud:     MQTT disconnected
2024.03.13 09:10:47.388 (wrn) custom:    MQTT disconnected
2024.03.13 09:10:47.566 (wrn) automation: MQTT disconnected
2024.03.13 09:10:48.006 (wrn) web:       MQTT disconnected
2024.03.13 09:10:49.272 (wrn) zigbee:    Device "Router" manufacturer name "easyiot.tech" and model name "UT-02" not found in library
2024.03.13 09:10:49.428 (wrn) cloud:     MQTT disconnected
2024.03.13 09:10:49.451 (wrn) custom:    MQTT disconnected
2024.03.13 09:10:49.481 (wrn) automation: MQTT disconnected
2024.03.13 09:10:49.950 (wrn) web:       MQTT disconnected
2024.03.13 09:10:49.961 (inf) zigbee:    15 devices loaded
2024.03.13 09:10:49.977 (inf) zigbee:    Properties restored
2024.03.13 09:10:50.004 (inf) zigbee:    Port "ttymxc1" opened successfully
2024.03.13 09:10:50.018 (inf) zigbee:    Resetting adapter (gpio)
2024.03.13 09:10:50.127 (wrn) zigbee:    MQTT disconnected
2024.03.13 09:10:50.288 (wrn) cloud:     Server connection error: QAbstractSocket::HostNotFoundError
2024.03.13 09:10:50.446 (inf) zigbee:    Adapter type: ZiGate 3.23
2024.03.13 09:10:50.759 (inf) zigbee:    ZiGate managed PAN ID: "0x55a4"
2024.03.13 09:10:50.768 (inf) zigbee:    Coordinator ready, address: 00:15:8d:00:04:32:d3:57
2024.03.13 09:10:51.449 (wrn) cloud:     MQTT disconnected
2024.03.13 09:10:51.458 (wrn) custom:    MQTT disconnected
2024.03.13 09:10:51.455 (wrn) automation: MQTT disconnected
2024.03.13 09:10:51.958 (wrn) web:       MQTT disconnected
2024.03.13 09:10:52.033 (wrn) zigbee:    MQTT disconnected
2024.03.13 09:10:53.603 (inf) custom:    MQTT connected
2024.03.13 09:10:53.606 (inf) cloud:     MQTT connected
2024.03.13 09:10:53.609 (inf) automation: MQTT connected
2024.03.13 09:10:53.647 (inf) automation: Service "custom" is online
2024.03.13 09:10:53.655 (inf) automation: Service "zigbee" is online
2024.03.13 09:10:53.809 (inf) automation: Service "custom" is online
2024.03.13 09:10:53.907 (wrn) automation: Service "zigbee" is offline
2024.03.13 09:10:54.012 (inf) zigbee:    MQTT connected
2024.03.13 09:10:54.017 (inf) web:       MQTT connected
2024.03.13 09:10:54.707 (inf) automation: Service "zigbee" is online
2024.03.14 08:44:03.633 (inf) automation: Sunrise set to 05:16 and sunset set to 17:07
2024.03.14 08:44:07.482 (inf) cloud:     Connected to server
**2024.03.14 08:45:30.679 (inf) zigbee:    Device "Свет в зале" status action request finished successfully
2024.03.14 08:45:35.945 (inf) zigbee:    Device "Свет в зале" status action request finished successfully
2024.03.14 08:54:03.672 (inf) zigbee:    Device "Лампа" status action request finished successfully
2024.03.14 08:54:08.777 (inf) zigbee:    Device "Лампа" color action request finished successfully
2024.03.14 08:54:16.154 (inf) zigbee:    Device "Лампа" status action request finished successfully** 

- **УДЯ управляет реальными устройствами штатно**

![изображение](https://github.com/u236/homed-service-custom/assets/77930301/1596b332-f166-4ece-8c0d-4dec200d83c9)

<img width="283" alt="изображение" src="https://github.com/u236/homed-service-custom/assets/77930301/d8d17388-0acc-465d-aa30-eff200f547f5">

**Comment by u236** [comment]
обновление, включающее в себя математические функции имеет отношение исключительно к службе автоматизаций и никак не трогает ни `homed-custom`, ни `homed-cloud`

из приложенного лога видно только что `homed-cloud` подключился к серверу, но это ничего не значит

нужно увидеть хотя бы конфигурацию (виртуальных) устройств, а лучше данные из топика `homed/status/custom`

я только что создал виртуальный выключатель и он тут же залетел в УДЯ с уведомлением, все работает, как и раньше

![IMAGE 2024-03-14 19:47:40](https://github.com/u236/homed-service-custom/assets/3758495/259c7aac-f35a-4356-9760-32fc4b646600)

**Comment by NE8XT** [comment]
<img width="700" alt="изображение" src="https://github.com/u236/homed-service-custom/assets/77930301/56f4a6fd-cd98-40e1-b547-42e28ddc3fac">

топик: homedom/status/custom

{"devices":[{"active":true,"cloud":true,"discovery":true,"exposes":["switch"],
"id":"101","name":"Охрана","real":false},{"active":true,"cloud":true,"discovery":true,"exposes":["switch"],
"id":"102","name":"Озон","real":false},{"active":true,"cloud":true,"discovery":true,"exposes":["switch"],
"id":"103","name":"Тревога","real":false},{"active":true,"cloud":**false**,"discovery":**false**,"exposes":["switch"],
"id":"104","name":"Солнце","real":false},{"active":true,"cloud":**false**,"discovery":**false**,"exposes":["switch"],
"id":"105","name":"Луна","real":false},{"active":true,"cloud":true,"discovery":true,"exposes":["switch"],
"id":"106","name":"Фонарь","real":false},{"active":true,"cloud":true,"discovery":true,"exposes":["switch"],
"id":"107","name":"Total Annihilation D-GUN","real":false},{"active":true,"cloud":true,"discovery":true,"exposes":["power"],
"id":"108","name":"Счетчик","options":{"power":{"class":"power","type":"sensor"}},"real":false}],"names":true,"timestamp":1710321053,"version":"1.0.5"}

<img width="376" alt="изображение" src="https://github.com/u236/homed-service-custom/assets/77930301/28433d31-cafa-4314-b9da-8b62358a24e4">

**Comment by u236** [comment]
исправлено на стороне сервера HOMEd Cloud
